#----------------------------------
# Database Configuration
#----------------------------------
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/starwarsapi
    username: starwars
    password: Starwars1@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


starwars:
    url: https://swapi.co/
    userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36